# CeLesteCMS Pro Cloudflare Configuration
name = "celestecms-pro"
compatibility_date = "2025-05-12"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = ".svelte-kit/cloudflare"

# Configure Cloudflare D1 Database
# After creating your D1 database with `wrangler d1 create celestecms-db`,
# replace the placeholder below with your actual database_id
[[d1_databases]]
binding = "DB"
database_name = "celestecms-db"
database_id = "d4fbe39b-a4b6-4a00-821d-f872b83b87ee" # D1 database ID

# Environment Variables
[vars]
# Public variables can be defined here
# Private variables should be set in the Cloudflare Dashboard or using wrangler
